# 10.2 数据聚合

## 10.2.1 逐列操作和多函数应用

In [1]:
import pandas as pd
import numpy as np
tips = pd.read_csv('../examples/tips.csv')
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [2]:
tips['tip_pct'] = tips['tip'] / tips['total_bill']
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [3]:
grouped = tips.groupby(['day', 'smoker'])
grouped_pct = grouped['tip_pct']
grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [4]:
grouped_pct.agg(['mean', 'std', 'min'])

                 mean       std       min
day  smoker
Fri  No      0.151650  0.028123  0.120385
     Yes     0.174783  0.051293  0.103555
Sat  No      0.158048  0.039767  0.056797
     Yes     0.147906  0.061375  0.035638
Sun  No      0.160113  0.042347  0.059447
     Yes     0.187250  0.154134  0.065660
Thur No      0.160298  0.038774  0.072961
     Yes     0.163863  0.039389  0.090014

In [5]:
grouped_pct.agg([('average', 'mean'), ('stdev', np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.024355
     Yes     0.174783  0.049553
Sat  No      0.158048  0.039323
     Yes     0.147906  0.060640
Sun  No      0.160113  0.041974
     Yes     0.187250  0.150023
Thur No      0.160298  0.038341
     Yes     0.163863  0.038213

In [6]:
functions = ['count', 'mean', 'max']
result = grouped[['tip_pct', 'total_bill']].agg(functions)
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [7]:
result['tip_pct']

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [8]:
ftuples = [('average','mean'), ('stdev', np.std)]
grouped[['tip_pct', 'total_bill']].agg(ftuples)

              tip_pct           total_bill
              average     stdev    average      stdev
day  smoker
Fri  No      0.151650  0.024355  18.420000   4.381467
     Yes     0.174783  0.049553  16.813333   8.778284
Sat  No      0.158048  0.039323  19.661778   8.839299
     Yes     0.147906  0.060640  21.276667   9.948545
Sun  No      0.160113  0.041974  20.506667   8.058556
     Yes     0.187250  0.150023  24.120000  10.163994
Thur No      0.160298  0.038341  17.113111   7.635449
     Yes     0.163863  0.038213  19.190588   8.105685

In [ ]:
# 传入as_index=False可以将分组键作为列而不是索引

# End