# 12. Python建模库介绍

# 12.1 pandas与模型代码的接口

In [1]:
import pandas as pd
data = pd.DataFrame({
    'x0':[1,2,3,4,5],
    'x1':[0.01,-0.01,0.25,-4.1,0.],
    'y':[-1.5,0.,3.6,1.3,-2.]
})
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [2]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [3]:
df2 = pd.DataFrame(data.to_numpy(), columns=['one','two','three'])
df2

   one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [5]:
model_col = ['one','two']
df2.loc[:,model_col].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [6]:
df2['category'] = pd.Categorical(['a','b','a','a','b'],categories=['a','b'])
df2

   one   two  three category
0  1.0  0.01   -1.5        a
1  2.0 -0.01    0.0        b
2  3.0  0.25    3.6        a
3  4.0 -4.10    1.3        a
4  5.0  0.00   -2.0        b

In [7]:
dummies = pd.get_dummies(df2.category,prefix='category')
data_with_dummies = df2.drop('category',axis=1).join(dummies)
data_with_dummies

   one   two  three  category_a  category_b
0  1.0  0.01   -1.5        True       False
1  2.0 -0.01    0.0       False        True
2  3.0  0.25    3.6        True       False
3  4.0 -4.10    1.3        True       False
4  5.0  0.00   -2.0       False        True

# End