# 6 数据加载、存储与文件格式

# 6.1 读写文本格式的数据

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('../examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
pd.read_csv('../examples/ex2.csv',names=['a','b','c','d','message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
pd.read_csv('../examples/ex2.csv',names=['a','b','c','d','message'],index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [9]:
parsed = pd.read_csv('../examples/csv_mindex.csv',index_col=['key1','key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
# 有些表格使用空格或其他分隔字段可以传入参数sep解决不规整问题
result = pd.read_csv('../examples/ex3.txt',sep='\\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [13]:
pd.read_csv('../examples/ex4.csv',skiprows=[0,2,3])  # 跳过第一行、第三行、第四行

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
result = pd.read_csv('../examples/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [16]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [17]:
# na_values参数可以指定哪些值应该被替换为NA/NaN
result = pd.read_csv('../examples/ex5.csv',na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [19]:
# pandas.read_csv函数参数
# path表示文件系统位置、URL、文件型对象的字符串
# skiprows 从文件开始处算起,需要忽略的行数或需要跳过的行数列表
# nrows 从文件开始处算起需要读取的行数
# parse_dates 尝试讲数据列解析为datetime对象,还可以指定需要解析的一组列号或列名的列表
# iterator 返回一个TextFileReader用于逐块读取文件
# chunksize 用于迭代的文件块大小

## 6.1.1 逐块读取文本文件

In [21]:
pd.options.display.max_rows=10
result = pd.read_csv('../examples/ex6.csv')
print(result)

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [22]:
pd.read_csv('../examples/ex6.csv',nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [23]:
chunker = pd.read_csv('../examples/ex6.csv',chunksize=1000)
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [25]:
# 迭代处理ex6.csv统计key
tot = pd.Series([],dtype='int64')
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(),fill_value=0)
tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64