# 6.2 二进制数据格式

In [1]:
import pandas as pd
frame = pd.read_csv('../examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [2]:
frame.to_pickle('../examples/frame_pickle')

In [3]:
pd.read_pickle('../examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
# HDF5 pytables

# End