# 7 数据清洗和准备

# 7.1 处理缺失数据

In [1]:
import pandas as pd
import numpy as np
float_data = pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [2]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [3]:
string_data = pd.Series(['aardvark',None,np.nan,'avocado'])
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

## 7.1.1 过滤缺失数据

In [4]:
data = pd.Series([1,np.nan,3.5,np.nan,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [6]:
# dropna默认丢弃任何含有缺失值的行 返回新对象而不修改原始对象
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [7]:
# 传入how
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
data[4] = np.nan
data.dropna(axis=1,how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = np.nan
df.iloc[:2,2] = np.nan
df

          0         1         2
0 -0.091947       NaN       NaN
1  0.946571       NaN       NaN
2  0.562903       NaN -0.111112
3 -0.210371       NaN  0.239276
4  0.576780  3.027706 -0.168361
5  1.210757 -0.292736  0.395589
6  0.395289  1.666599  0.030575

In [11]:
df.dropna()

          0         1         2
4  0.576780  3.027706 -0.168361
5  1.210757 -0.292736  0.395589
6  0.395289  1.666599  0.030575

In [13]:
# thresh指定每行/列至少需要有多少个非空值才能保留
df.dropna(thresh=2)

          0         1         2
2  0.562903       NaN -0.111112
3 -0.210371       NaN  0.239276
4  0.576780  3.027706 -0.168361
5  1.210757 -0.292736  0.395589
6  0.395289  1.666599  0.030575

## 7.1.2填充缺失数据

In [14]:
df.fillna(0)

          0         1         2
0 -0.091947  0.000000  0.000000
1  0.946571  0.000000  0.000000
2  0.562903  0.000000 -0.111112
3 -0.210371  0.000000  0.239276
4  0.576780  3.027706 -0.168361
5  1.210757 -0.292736  0.395589
6  0.395289  1.666599  0.030575

In [15]:
# 若调用fillna时使用字典就可以实现对不同列填充不同的值
df = df.round(2)
df

      0     1     2
0 -0.09   NaN   NaN
1  0.95   NaN   NaN
2  0.56   NaN -0.11
3 -0.21   NaN  0.24
4  0.58  3.03 -0.17
5  1.21 -0.29  0.40
6  0.40  1.67  0.03

In [16]:
df.fillna({1:0.5,2:0})

      0     1     2
0 -0.09  0.50  0.00
1  0.95  0.50  0.00
2  0.56  0.50 -0.11
3 -0.21  0.50  0.24
4  0.58  3.03 -0.17
5  1.21 -0.29  0.40
6  0.40  1.67  0.03

In [17]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = np.nan
df.iloc[4:,2] = np.nan
df

          0         1         2
0  1.189302  1.350743  0.435079
1 -0.005511  0.147651  0.699010
2 -0.135149       NaN -2.220339
3  0.673503       NaN -1.825343
4  0.170935       NaN       NaN
5 -1.082156       NaN       NaN

In [19]:
df.ffill()  # 前向填充

          0         1         2
0  1.189302  1.350743  0.435079
1 -0.005511  0.147651  0.699010
2 -0.135149  0.147651 -2.220339
3  0.673503  0.147651 -1.825343
4  0.170935  0.147651 -1.825343
5 -1.082156  0.147651 -1.825343

In [20]:
# 限制只能填充2个
df.ffill(limit=2)

          0         1         2
0  1.189302  1.350743  0.435079
1 -0.005511  0.147651  0.699010
2 -0.135149  0.147651 -2.220339
3  0.673503  0.147651 -1.825343
4  0.170935       NaN -1.825343
5 -1.082156       NaN -1.825343

In [21]:
# 横向填充
print(df.ffill(axis=1))

          0         1         2
0  1.189302  1.350743  0.435079
1 -0.005511  0.147651  0.699010
2 -0.135149 -0.135149 -2.220339
3  0.673503  0.673503 -1.825343
4  0.170935  0.170935  0.170935
5 -1.082156 -1.082156 -1.082156

In [ ]:
# bfill后向填充也一样

# End