# Series

## 1.Series创建

In [30]:
import pandas as pd
import numpy as np
s = pd.Series([1,2,3,4,5])
print(s)
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],name='value')
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: value, dtype: int64

In [31]:
s1 = pd.Series(s,index=['a','c','e'])
print(s1)

a    1
c    3
e    5
Name: value, dtype: int64

## 2.Series属性

In [32]:
print(s.index)
print(s.values)
print(s.shape)
print(s.ndim)
print(s.dtype)
print(s.name)
print(s.loc['a':'c'])   # 显式索引 支持切片
print(s.iloc[1])   # 隐式索引

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
(5,)
1
int64
value
a    1
b    2
c    3
Name: value, dtype: int64
2

In [33]:
print(s['a'])
print(s[s<3])
s['f']=6
print(s)
print(s.head(2))
print(s.tail(2))

1
a    1
b    2
Name: value, dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
Name: value, dtype: int64
a    1
b    2
Name: value, dtype: int64
e    5
f    6
Name: value, dtype: int64

## 3.常用方法

In [34]:
s = pd.Series([10,2,np.nan,None,3,4,5],index=['a','b','c','d','e','f','g'])
print(s)

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
dtype: float64

In [35]:
s.head()

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
dtype: float64

In [36]:
s.tail(3)

e    3.0
f    4.0
g    5.0
dtype: float64

In [37]:
# 所有描述性信息
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
dtype: float64

In [38]:
# 获取元素个数
s.count()

np.int64(5)

In [39]:
print(s.keys())
print(s.index)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [40]:
print(s.isna())

a    False
b    False
c     True
d     True
e    False
f    False
g    False
dtype: bool

In [41]:
s.isin([4,5])

a    False
b    False
c    False
d    False
e    False
f     True
g     True
dtype: bool

In [42]:
# mean max min var std median略去
s.sort_values()

b     2.0
e     3.0
f     4.0
g     5.0
a    10.0
c     NaN
d     NaN
dtype: float64

In [43]:
print(s.idxmax())   # 返回最大值索引
print(s.idxmin())   # 返回最小值索引

a
b

In [44]:
s.quantile(0.25)   # 分位数 和numpy不同

np.float64(3.0)

In [45]:
s['a']=2
s.mode()
s.value_counts()

2.0    2
3.0    1
4.0    1
5.0    1
Name: count, dtype: int64

In [46]:
# 去重
s.drop_duplicates()   # 返回Series

a    2.0
c    NaN
e    3.0
f    4.0
g    5.0
dtype: float64

In [47]:
s.unique()   # 返回array

array([ 2., nan,  3.,  4.,  5.])

In [48]:
print(s.nunique())   # 去重后元素个数

4

In [49]:
s.sort_index()

a    2.0
b    2.0
c    NaN
d    NaN
e    3.0
f    4.0
g    5.0
dtype: float64

In [50]:
s.diff()   # 差值

a    NaN
b    0.0
c    NaN
d    NaN
e    NaN
f    1.0
g    1.0
dtype: float64

In [51]:
s.pct_change(fill_method=None)   # 变化率

a         NaN
b    0.000000
c         NaN
d         NaN
e         NaN
f    0.333333
g    0.250000
dtype: float64

# pandas dataframe

In [52]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df1 = pd.DataFrame({'第一列':s1,'第二列':s2})
print(df1)
df = pd.DataFrame(
    {
        'id':[1,2,3,4,5],
        'name':['a','b','c','d','e'],
        'age':[10,20,30,40,50]
    },index=[1,2,3,4,5],columns=['id','age','name']   # columns可以调整类的顺序
)
print(df)

   第一列  第二列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10
   id  age name
1   1   10    a
2   2   20    b
3   3   30    c
4   4   40    d
5   5   50    e

In [55]:
print(df.index)   # 行索引
print(df.columns)   # 列标签
print(df.values)
# print(df.ndim)
# print(df.dtypes)
print(df.shape)
print(df.size)

Index([1, 2, 3, 4, 5], dtype='int64')
Index(['id', 'age', 'name'], dtype='object')
[[1 10 'a']
 [2 20 'b']
 [3 30 'c']
 [4 40 'd']
 [5 50 'e']]
(5, 3)
15

In [56]:
print(df.T)

       1   2   3   4   5
id     1   2   3   4   5
age   10  20  30  40  50
name   a   b   c   d   e

In [58]:
print(df.loc[4])
print(df.iloc[3])

id       4
age     40
name     d
Name: 4, dtype: object
id       4
age     40
name     d
Name: 4, dtype: object

In [60]:
print(df.loc[2:,'name'])
print(df.iloc[:,0])

2    b
3    c
4    d
5    e
Name: name, dtype: object
1    1
2    2
3    3
4    4
5    5
Name: id, dtype: int64

In [62]:
print(df.at[3,'age'])
print(df.iat[0,1])   # loc,iloc同at,iat

30
10

In [63]:
print(df['name'])   # 获取name这一列 同at,loc
print(df.name)

1    a
2    b
3    c
4    d
5    e
Name: name, dtype: object
1    a
2    b
3    c
4    d
5    e
Name: name, dtype: object

In [64]:
# 多列数据访问
print(df[['name','age']])

  name  age
1    a   10
2    b   20
3    c   30
4    d   40
5    e   50

In [68]:
df[(df.age>20) & (df.id<5)]

   id  age name
3   3   30    c
4   4   40    d

In [69]:
# 随机抽样
df.sample(2)

   id  age name
4   4   40    d
3   3   30    c

In [70]:
print(df.head(2))
print(df.tail(2))

   id  age name
1   1   10    a
2   2   20    b
   id  age name
4   4   40    d
5   5   50    e

In [71]:
df

   id  age name
1   1   10    a
2   2   20    b
3   3   30    c
4   4   40    d
5   5   50    e

In [75]:
print(df.isin(['f',20]))

      id    age   name
1  False  False  False
2  False   True  False
3  False  False  False
4  False  False  False
5  False  False  False

In [76]:
print(df.isna())

      id    age   name
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [79]:
print(df.age.sum())
print(df.age.describe())
print(df.age.mean())
print(df.age.median())
print(df.age.quantile(0.25))
print(df.age.mode())
print(df.age.max())
print(df.age.min())
print(df.age.var())
print(df.count())   # 每列非缺失值的元素个数
print(df.value_counts())
df.drop_duplicates()
df.duplicated()   # 返回每行是否重复
df.duplicated(subset=['age'])   # 返回列是否重复
df.replace(20,30)   # 所有20变30

150
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
Name: age, dtype: float64
30.0
30.0
20.0
0    10
1    20
2    30
3    40
4    50
Name: age, dtype: int64
50
10
250.0
id      5
age     5
name    5
dtype: int64

In [80]:
df.cummax()
df.cummin()   # 想改变方向可以在括号里加axis=1 保证行方向不能有字符串

   id  age name
1   1   10    a
2   1   10    a
3   1   10    a
4   1   10    a
5   1   10    a

In [81]:
df.sort_index()
df.sort_values(by=['age','id'],ascending=[False,True])   # 想降序可以加ascending=False  字典序
df.nlargest(2,columns=['age','id'])
# nsmallest同理

   id  age name
5   5   50    e
4   4   40    d