In [7]:
import pandas as pd
import numpy as np
data = pd.DataFrame(
    {
        'maths':[85,92,78,88,95],
        'english':[90,88,85,92,80],
        'physics':[75,80,88,85,90]
    },index=['张三','李四','王五','赵六','钱七'],columns=['maths','english','physics']
)
data

    maths  english  physics
张三     85       90       75
李四     92       88       80
王五     78       85       88
赵六     88       92       85
钱七     95       80       90

In [8]:
data.sum(axis=1)

张三    250
李四    260
王五    251
赵六    265
钱七    265
dtype: int64

In [13]:
data[(data.maths>90) & (data.english>85)]

    maths  english  physics
李四     92       88       80

In [16]:
data.sort_values(by='total',ascending=False)

    maths  english  physics  total
钱七     95       80       90    265
赵六     88       92       85    265
李四     92       88       80    260
王五     78       85       88    251
张三     85       90       75    250

In [19]:
data.nlargest(n=2,columns=['total','maths'])

    maths  english  physics  total
钱七     95       80       90    265
赵六     88       92       85    265